# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c646033c8e33fa9980f0ad615ac25856a6fb447b80d3aed38f907f7f3a79511238000bfdee54deb2fd60ad8da148c9500334bc32cafe09ed190fc0d22c844d2b

test:
  secret_key_base: b727ed9e8677c937adc240a57ad02e52050042dc13c4f38d29a8e5922a7d3a6dee52377a937fcc49de7d896842491c8257bb23d68ed66e1e3526498334460017

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
